### ISSUE TITLE
Improve UX for initial loading on site frontend

### ISSUE THREAD

**Issue by jeffpaul** [10up/retro-winamp-block#15] opened 2021-11-13 00:49 UTC
**Is your enhancement related to a problem? Please describe.**
 From @dkotter in #6:
> On the FE, right now it renders out the audio players and then those get replaced with the WebAmp player. Thinking some basic styling here where those players get hidden and maybe some sort of placeholder container, so once the player loads in it's not shifting the page contents around

**Describe the solution you'd like**
 Review the work in #6, the current state of the develop branch, and what approach should (if any) be taken to resolve this issue.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeffpaul** [comment] 2022-06-28 21:34
@fabiankaegy any tweaks you might recommend on initial UX here?

**Comment by iansvo** [comment] 2022-11-02 16:47
@jeffpaul Can you confirm if this is still needed? Seems to be a duplicate of #38.

**Comment by mehul0810** [comment] 2023-01-22 02:31
@jeffpaul After doing some research in admin and frontend, there are couple of items I have noted:

- With Winamp block in admin, when I click on "Preview Player" then the player always sticks to the top making it really hard for the first time user to get back to normal player mode until the user refreshes the page or try scrolling as the player it sticked at the top scrolling helps  to show the option and then we can change it to normal player mode from preview. The editorial experience around this needs some improvement See screenshot: <img width="1048" alt="Screenshot 2023-01-22 at 7 52 21 AM" src="https://user-images.githubusercontent.com/1852711/213897731-efbd8462-6221-4b5e-80a9-9c49cf17f699.png">
- The player in the frontend looks good. However, I feel there are couple of things that might need improvement:
- - The player buttons looks disabled irrespective of it being enabled/disabled
- - The player can be moved around on the page overlapping the content but that leaves a space where it was originally placed. So, wondering if moving around of player is a feature then can we make the whitespace to be moved around along with it? 💭 
<img width="1100" alt="Screenshot 2023-01-22 at 8 00 36 AM" src="https://user-images.githubusercontent.com/1852711/213897909-d1cbce2f-7b86-430c-bc69-db49a5fb5eab.png">


_**Note:** I think all the items I mentioned should not be a problem. But, just wanted to add my experience being a new user._

**Comment by Sidsector9** [comment] 2023-01-24 12:36
@jeffpaul this maybe already fixed as part of some other PR.

While testing:
- The audio HTML element is always hidden.
- The WinAmp container has a min-height which prevents layout shifts.

As of now, we just have a plain empty container until the player loads. We can improvise that if needed in a separate enhancement issue.

@mehul0810 can you open that as a separate ticket? It will be easier to track that way.

**Comment by mehul0810** [comment] 2023-01-29 03:35
@Sidsector9 Thanks for reviewing. I have created the issue #83

**Comment by jeffpaul** [comment] 2023-02-06 17:23
It looks like we could build upon the work in Gutenberg 14.7/14.6 in adding https://github.com/WordPress/gutenberg/pull/45875 && https://github.com/WordPress/gutenberg/pull/45300 such that we can set the default height of the block (based upon the components enabled: player, playlist, visualizations, etc).  This will likely mean we need to bump the WP minimum to 6.2 as I believe these Gutenberg updates will be in core then, so a PR to handle for this is not a near-term need but something we should aim for in testing for WP 6.2 compat later in March.

**Comment by av3nger** [comment] 2023-04-04 03:19
I wasn't able to replicate any CLS or content layout replacement happening on FE. It looks like all the skins default to the same size, which is already pre-set via CSS.

**Closed** 2023-04-05 15:13 UTC
Labels: type:enhancement, help wanted
